FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY src/services/webapi/VCommerce.Api/VCommerce.Api.csproj src/services/webapi/VCommerce.Api/
RUN dotnet restore src/services/webapi/VCommerce.Api/VCommerce.Api.csproj

COPY . .

WORKDIR /src/src/services/webapi/VCommerce.Api
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
ENV JWT__SecretKey="x0HhzrgVfOJgG3V6Hpl9Ev9ccojN+bfZxPxX5TWi6uY="
COPY --from=publish /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "VCommerce.Api.dll"]
    