version: "3.8"

services:
  vcommerce-db-server:
    image: bitnami/postgresql
    container_name: vcommerce-db-server
    hostname: vcommerce-db-server
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=vcommerce_db
    volumes:
      - vcommerce_db_data:/bitnami/postgresql

  vcommerce-api:
    build:
      context: .
      dockerfile: src/services/webapi/VCommerce.Api/Dockerfile
    container_name: vcommerce-api
    depends_on:
      - vcommerce-db-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=vcommerce-db-server;Port=5432;Database=vcommerce_db;Username=postgres;Password=postgres
    ports:
      - 5000:80

  vcommerce-mvc:
    build:
      context: .
      dockerfile: src/services/webapp/VCommerce.Mvc/Dockerfile
    container_name: vcommerce-mvc
    depends_on:
      - vcommerce-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiBaseUrl=http://vcommerce-api:80
    ports:
      - 5001:80

volumes:
  vcommerce_db_data:
