services:
  vcommerce-db-server:
    image: bitnami/postgresql
    container_name: vcommerce-db-server
    hostname: vcommerce-db-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=vcommerce_db
    volumes:
      - vcommerce_db_data:/bitnami/postgresql

volumes:
  vcommerce_db_data: