FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY src/services/webapp/VCommerce.Mvc/VCommerce.Mvc.csproj src/services/webapp/VCommerce.Mvc/
RUN dotnet restore src/services/webapp/VCommerce.Mvc/VCommerce.Mvc.csproj

COPY . .

WORKDIR /src/src/services/webapp/VCommerce.Mvc
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 8081
ENTRYPOINT ["dotnet", "VCommerce.Mvc.dll"]
