# fly.toml app configuration file generated for vcommerce-api on 2025-05-27T09:00:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vcommerce-api'
primary_region = 'gig'

[build]
  dockerfile = "Dockerfile"
  context = "."

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
